name: Android CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  apk:
    name: Generar APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Configurar JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: gradle
      
      - name: Ajustar permisos de ejecucion de Gradle
        run: chmod +x gradlew
        
      - name: Compilar aplicacion con Gradle
        run: ./gradlew assembleDebug --stacktrace
        
      - name: Subir archivo APK
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: app/build/outputs/apk/debug/check.apk