name: Integracion Continua de Android

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v3

       - name: Configurar JDK 11
         uses: actions/setup-java@v3
         with:
           java-version: '11'
           cache: gradle
        
       - name: Ajustar permisos de ejecucion de Gradle
         run: chmod +x gradlew

       - name: Compilar aplicacion con Gradle
         run: ./gradlew build

       - name: Subir archivo APK
         uses: actions/upload-artifact@v3
         with:
           name: check
           path: app/build/outputs/apk/develop/check.apk
