name: SonarCloud

on:
  push:
    branches: [ "main" , "develop" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  sonar:
    name: Analizar el proyecto mediante Sonar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Configurar JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: "8"
          
      - name: Ajustar permisos de ejecucion de Gradle
        run: chmod +x gradlew  
          
      - name: Limpiar cache
        run: ./gradlew clean
        
      - name: Compilar y analizar el codigo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build sonarqube --scan
