name: SonarCloud

on:
  push:
    branches: [ "main" , "develop" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  sonar:
    name: Analizar el proyecto mediante Sonar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Configurar JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: gradle
          
      - name: Ajustar permisos de ejecucion de Gradle
        run: chmod +x gradlew  
          
      - name: Limpiar cache de Gradlew
        run: ./gradlew clean
      
      - name: Limpiar cache de Sonar
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
        
      - name: Compilar y analizar el codigo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar
