name: SonarCloud

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

permissions:
  pull-requests: read

jobs:
  analisis:
    name: Analisis mediante SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Analizar el codigo mediante SonarCloud
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Analizar el codigo mediante SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=blue-person_check-in-app
            -Dsonar.organization=blue-person
