name: SonarCloud

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

permissions:
  pull-requests: read

jobs:
  analisis:
    runs-on: ubuntu-latest

    steps:
      - name: Analizar el codigo mediante SonarCloud

        uses: SonarSource/sonarcloud-github-action@de2e56b42aa84d0b1c5b622644ac17e505c9a049
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=blue-person_check-in-app
            -Dsonar.organization=blue-person
